[datasets]


#########
# IGANG #
#########

    [datasets.igang_videregaaende]
    team = "utd-vg"
    bucket = "vgu"
    path_glob = ""
    variables = [
        "fnr",
        "snr",
        #"snr_mrk",  # We dont demand this delivered, as we will reproduce anyway
        "pers_foedselsdato",
        "pers_kjoenn",
        "utd_skoleaar_start",
        "utd_aktivitet_start",
        "utd_aktivitet_start_inn",
        "utd_aktivitetsnivaa_heltid_deltid",
        "bof_orgnrbed",
        "utd_orgnr",
        "nus2000",
        "utd_viderutd_nettbasert",
        "utd_datakilde",
        "utd_klassetrinn",
        "utd_utdanningstype",
        "utd_utveksling",
        "utd_skolekom",
        "gro_skolenr_inn",
        "gro_elevstatus",
        "gro_programomraade",
        "vg_utdprogram",
        "vg_rettstype_inntak",
        "vg_antall_aarstimer_elevkurs",
        "vg_antall_fag_elevkurs",
        "vg_kursprosent",
        "vg_kontraktstype",
        "vg_ernylaerling",
        "vg_yrkes_og_studiekompetanse",
        "vg_hovedaktivitet",
        ]

        [datasets.igang_videregaaende.thresholds_empty]
            fnr = 0.0


    [datasets.igang_fagskole]
        team = "utd-uhfagskole"
        bucket = "fagskole"
        path_glob = ""
        variables = [
        "fnr",
        "snr",
        #"snr_mrk",  # We dont demand this delivered, as we will reproduce anyway
        "pers_foedselsdato",
        "pers_kjoenn",
        "utd_skoleaar_start",
        "utd_aktivitet_start",
        "utd_aktivitet_start_inn",
        "utd_aktivitetsnivaa_heltid_deltid",
        "bof_orgnrbed",
        "utd_orgnr",
        "nus2000",
        "utd_viderutd_nettbasert",
        "utd_datakilde",
        "utd_klassetrinn",
        "utd_utdanningstype",
        "utd_utveksling",
        "utd_skolekom",
        #"utd_studieland",
        #"fa_ergodkjent_fagskoleutd",  # skal utledes fra nus2000 isteden
        "fa_utveksl_varighet_dager",
        "fa_studiestednr_inn",
        "fa_hovedaktivitet",
        "fuh_nett_eller_stedbasert",
        "fa_institusjon_id",
        "fuh_opptaksgrunnlag",
        "fuh_utvekslingsland",
        "fa_tilbudskode",
        "fa_tilbudsnavn",
        "fa_nettbasert_antall_samledager_tilbud",
        ]

    [datasets.igang_fagskole.thresholds_empty]
        fnr = 0.0


    [datasets.igang_hoeyereutdanning]
        team = "utd-uhfagskole"
        bucket = "uh"
        path_glob = ""

        variables = [
        "fnr",
        "snr",
        #"snr_mrk",   # We dont demand this delivered, as we will reproduce anyway
        "pers_foedselsdato",
        "pers_kjoenn",
        "utd_skoleaar_start",
        "utd_aktivitet_start",
        "utd_aktivitet_start_inn",
        "utd_aktivitetsnivaa_heltid_deltid",
        "bof_orgnrbed",
        "utd_orgnr",
        "nus2000",
        "utd_viderutd_nettbasert",
        "utd_datakilde",
        "utd_klassetrinn",
        "utd_utdanningstype",
        "utd_utveksling",
        "utd_skolekom",
        "fuh_nett_eller_stedbasert",
        "fuh_opptaksgrunnlag",
        "fuh_utvekslingsland",
        "uh_institusjon_id",
        "uh_erpermisjon",
        "uh_statsborgerskap_inn",
        "uh_studierett",
        "uh_studienivaa",
        "uh_utdplan",
        "uh_studieprogram",
        "uh_studieprogresjon_hoest",
        #"uh_erutland",
        "uh_studgrunnlagsland",
        "utd_studieland",
        "uh_utvekslingsavtale",
        "uh_undervisningsspraak",
        "uh_campus_kommune",
        "uh_campus_sted",
        "uh_hovedaktivitet",
        ]

        [datasets.igang_hoeyereutdanning.thresholds_empty]
            fnr = 0.0

############
# AVSLUTTA #
############

    [datasets.avslutta_grunnskole]
    team = "utd-bhgskole"
    bucket = ""
    path_glob = ""

        variables = [
	        "fnr",
            "snr",
            #"snr_mrk",  # We dont demand this delivered, as we will reproduce anyway
            "pers_foedselsdato",
            "pers_kjoenn",
            "nus2000",
            "utd_skoleaar_start",
            "utd_aktivitet_start",
            "utd_aktivitet_slutt",
            "utd_aktivitet_start_inn",
            "utd_aktivitet_slutt_inn",
            "utd_datakilde",
            "utd_klassetrinn",
            "utd_utdanningstype",
            "utd_fullfoertkode",
            "utd_aktivitetsnivaa_heltid_deltid",
            "bof_orgnrbed",
            "utd_skolekom",
            "utd_orgnr",
            "utd_viderutd_nettbasert",
            "gr_grunnskolepoeng",
            "gro_fravaer_dager",
            "gro_fravaer_timer",
            "gro_programomraade",
            "gro_elevstatus",
            "gro_skolenr_inn",
            "gro_skolenavn_inn",


        ]

        [datasets.avslutta_grunnskole.thresholds_empty]
            fnr = 0.0



    [datasets.avslutta_videregaaende]
        team = "utd-vg"
        bucket = "vgu"
        path_glob = ""

        variables = [
	        "fnr",
            "snr",
            #"snr_mrk",  # We dont demand this delivered, as we will reproduce anyway
            "pers_foedselsdato",
            "pers_kjoenn",
            "utd_skoleaar_start",
            "utd_aktivitet_start",
            "utd_aktivitet_slutt",
            "utd_aktivitet_start_inn",
            "utd_aktivitet_slutt_inn",
            "utd_aktivitetsnivaa_heltid_deltid",
            "bof_orgnrbed",
            "utd_orgnr",
            "nus2000",
            "utd_datakilde",
            "utd_klassetrinn",
            "utd_utdanningstype",
            "utd_skolekom",
            "utd_fullfoertkode",
            "utd_viderutd_nettbasert",
            "gro_fravaer_dager",
            "gro_fravaer_timer",
            "gro_skolenr_inn",
            "gro_elevstatus",
            "gro_programomraade",
            "vg_utdprogram",
            "vg_rettstype_inntak",
            "vg_kursprosent",
            "vg_karakterpoeng",
            "vg_ervedtak_saer_spraak",
            "vg_bevistype",
            "vg_proevekandtype",
            "vg_proevenr",
            "vg_proeve_dato",
            "vg_fullfoertkode_detaljert",
        ]
        [datasets.avslutta_videregaaende.thresholds_empty]
            fnr = 0.0

    [datasets.avslutta_fagskole]
        team = "utd-uhfagskole"
        bucket = "fagskole"
        path_glob = ""
        variables = [
	        "fnr",
            "snr",
            #"snr_mrk",  # We dont demand this delivered, as we will reproduce anyway
            "pers_foedselsdato",
            "pers_kjoenn",
            "utd_skoleaar_start",
            "utd_aktivitet_start",
            "utd_aktivitet_slutt",
            "utd_aktivitet_start_inn",
            "utd_aktivitet_slutt_inn",
            "utd_aktivitetsnivaa_heltid_deltid",
            "bof_orgnrbed",
            "utd_orgnr",
            "nus2000",
            "utd_datakilde",
            "utd_klassetrinn",
            "utd_utdanningstype",
            "utd_skolekom",
            #"utd_studieland",
            "utd_fullfoertkode",
            "utd_viderutd_nettbasert",
            #"fa_ergodkjent_fagskoleutd",  # skal utledes fra nus2000 isteden
            "fa_studiestednr_inn",
            "fa_institusjon_id",
            "fa_karakter",
            "fuh_nett_eller_stedbasert",
            "fa_tilbudskode",
            "fa_tilbudsnavn",
            "fa_nettbasert_antall_samledager_tilbud",
        ]

    [datasets.avslutta_fagskole.thresholds_empty]
            fnr = 0.0


    [datasets.avslutta_hoeyereutdanning]
        team = "utd-uhfagskole"
        bucket = "uh"
        path_glob = ""

        variables = [
            "fnr",
            "snr",
            #"snr_mrk",  # We dont demand this delivered, as we will reproduce anyway
            "pers_foedselsdato",
            "pers_kjoenn",
            "utd_skoleaar_start",
            "utd_aktivitet_start",
            "utd_aktivitet_slutt",
            "utd_aktivitet_start_inn",
            "utd_aktivitet_slutt_inn",
            "utd_aktivitetsnivaa_heltid_deltid",
            "bof_orgnrbed",
            "utd_orgnr",
            "nus2000",
            "utd_datakilde",
            "utd_klassetrinn",
            "utd_utdanningstype",
            "utd_skolekom",
            "utd_fullfoertkode",
            "utd_viderutd_nettbasert",
            "fuh_nett_eller_stedbasert",
            "uh_institusjon_id",
            "uh_statsborgerskap_inn",
            "uh_studierett",
            "uh_studienivaa",
            "uh_studieprogram",
            "utd_studieland",
            #"uh_erutland",
            "uh_fakultet",
            "uh_studiepoeng_grad",
            "uh_campus_kommune",
            "uh_campus_sted",
            "uh_ervitnemaalsgivende",
        ]

        [datasets.avslutta_hoeyereutdanning.thresholds_empty]
            fnr = 0.0



###########
# EKSAMEN #
###########



    [datasets.eksamen_hoeyereutdanning]
        team = "utd-uhfagskole"
        bucket = "uh"
        path_glob = ""
        variables = [
            "fnr",
            "snr",
            #"snr_mrk",  # We dont demand this delivered, as we will reproduce anyway
            "pers_foedselsdato",
            "pers_kjoenn",
            "utd_skoleaar_start",
            "bof_orgnrbed",
            "utd_orgnr",
            "nus2000",
            "utd_datakilde",
            "utd_utdanningstype",
            "utd_skolekom",
            "utd_viderutd_nettbasert",
            "fuh_nett_eller_stedbasert",
            "uh_eksamen_dato",
            "uh_eksamen_dato_inn",
            "uh_antall_deleksamener",
            "uh_antall_deleksamener_bestatt",
            "uh_eksamen_ergjentak",
            "uh_eksamen_karakter",
            "uh_eksamen_studpoeng",
            "uh_emnekode",
            "uh_emnekode_navn",
            "uh_institusjon_id",
            "uh_studienivaa",
            "uh_studieprogram",
            "uh_studieprogram_navn",
            "uh_studierett",
            "uh_termin_rapportert",
            "uh_fullfoertkode_inn",
            "uh_campus_kommune",
            "uh_campus_sted",
        ]

    [datasets.eksamen_hoeyereutdanning.thresholds_empty]
            fnr = 0.0
