[datasets]

    [datasets.avslutta_grunnskole]

        variables = [
	        "fnr",
            "snr",
            "pers_foedselsdato",
            "pers_kjoenn",
            "nus2000",
            "gr_grunnskolepoeng",
            "gro_fravaer_dager",
            "gro_fravaer_timer",
            "gro_programomraade",
            "gro_elevstatus",
            "gro_skolenr_inn",
            "utd_skoleaar_start",
            "utd_aktivitetsnivaa_heltid_deltid",
            "utd_aktivitet_slutt",
            "utd_aktivitet_slutt_inn",
            "utd_datakilde",
            "utd_klassetrinn",
            "utd_utdanningstype",
            "utd_fullfoertkode",
            "bof_orgnrbed",
            "utd_skolekom",
            "utd_orgnr",
            "utd_viderutd_nettbasert",


        ]

        [datasets.avslutta_grunnskole.thresholds_empty]
            fnr = 0.0
