[datasets]


#########
# IGANG #
#########

[datasets.igang_videregaaende]

    variables = [
        "fnr",
        "snr",
        "pers_foedselsdato",
        "pers_kjoenn",
        "utd_skoleaar_start",
        "utd_aktivitet_start",
        "utd_aktivitet_start_inn",
        "utd_aktivitetsnivaa_heltid_deltid",
        "bof_orgnrbed",
        "utd_orgnr",
        "nus2000",
        "utd_viderutd_nettbasert",
        "utd_datakilde",
        "utd_klassetrinn",
        "utd_utdanningstype",
        "utd_utveksling",
        "utd_skolekom",
        "gro_skolenr_inn",
        "gro_elevstatus",
        "gro_programomraade",
        "vg_rettstype_inntak",
        "vg_antall_aarstimer_elevkurs",
        "vg_antall_fag_elevkurs",
        "vg_kursprosent",
        "vg_kontraktstype",
        "vg_nylaerling",
        "vg_yrkes_og_studiekompetanse",
        "vg_hovedaktivitet",
        "fuh_nett_eller_stedbasert",
        ]

    [datasets.igang_videregaaende.thresholds_empty]
            fnr = 0.0


[datasets.igang_fagskole]

    variables = [
        "fnr",
        "snr",
        "pers_foedselsdato",
        "pers_kjoenn",
        "utd_skoleaar_start",
        "utd_aktivitet_start",
        "utd_aktivitet_start_inn",
        "utd_aktivitetsnivaa_heltid_deltid",
        "bof_orgnrbed",
        "utd_orgnr",
        "nus2000",
        "utd_viderutd_nettbasert",
        "utd_datakilde",
        "utd_klassetrinn",
        "utd_utdanningstype",
        "utd_utveksling",
        "utd_skolekom",
        "fa_godkjent_fagskoleutd",
        "fa_utveksl_varighet_dager",
        "fa_studiestednr_inn",
        "fa_hovedaktivitet",
        "fuh_nett_eller_stedbasert",
        "fuh_opptaksgrunnlag",
        "fuh_utvekslingsland",
        ]

    [datasets.igang_fagskole.thresholds_empty]
        fnr = 0.0


[datasets.igang_hoyereutdanning]

    variables = [
        "fnr",
        "snr",
        "pers_foedselsdato",
        "pers_kjoenn",
        "utd_skoleaar_start",
        "utd_aktivitet_start",
        "utd_aktivitet_start_inn",
        "utd_aktivitetsnivaa_heltid_deltid",
        "bof_orgnrbed",
        "utd_orgnr",
        "nus2000",
        "utd_viderutd_nettbasert",
        "utd_datakilde",
        "utd_klassetrinn",
        "utd_utdanningstype",
        "utd_utveksling",
        "utd_skolekom",
        "fa_godkjent_fagskoleutd",
        "fa_utveksl_varighet_dager",
        "fa_studiestednr_inn",
        "fa_hovedaktivitet",
        "fuh_nett_eller_stedbasert",
        "fuh_opptaksgrunnlag",
        "fuh_utvekslingsland",
        ]

    [datasets.igang_hoyereutdanning.thresholds_empty]
            fnr = 0.0

############
# AVSLUTTA #
############

    [datasets.avslutta_grunnskole]

        variables = [
	        "fnr",
            "snr",
            "pers_foedselsdato",
            "pers_kjoenn",
            "nus2000",
            "gr_grunnskolepoeng",
            "gro_fravaer_dager",
            "gro_fravaer_timer",
            "gro_programomraade",
            "gro_elevstatus",
            "gro_skolenr_inn",
            "utd_skoleaar_start",
            "utd_aktivitetsnivaa_heltid_deltid",
            "utd_aktivitet_slutt",
            "utd_aktivitet_slutt_inn",
            "utd_datakilde",
            "utd_klassetrinn",
            "utd_utdanningstype",
            "utd_fullfoertkode",
            "bof_orgnrbed",
            "utd_skolekom",
            "utd_orgnr",
            "utd_viderutd_nettbasert",
        ]

        [datasets.avslutta_grunnskole.thresholds_empty]
            fnr = 0.0



[datasets.avslutta_videregaaende]

        variables = [
	        "fnr",
            "snr",
            "pers_foedselsdato",
            "pers_kjoenn",
            "utd_skoleaar_start",
            "utd_aktivitet_start",
            "utd_aktivitet_slutt",
            "utd_aktivitet_start_inn",
            "utd_aktivitet_slutt_inn",
            "utd_aktivitetsnivaa_heltid_deltid",
            "bof_orgnrbed",
            "utd_orgnr",
            "nus2000",
            "utd_datakilde",
            "utd_klassetrinn",
            "utd_utdanningstype",
            "utd_skolekom",
            "utd_fullfoertkode",
            "utd_viderutd_nettbasert",
            "gro_fravaer_dager",
            "gro_fravaer_timer",
            "gro_skolenr_inn",
            "gro_elevstatus",
            "gro_programomraade",
            "vg_rettstype_inntak",
            "vg_kursprosent",
            "vg_fullfoertkode_detaljert",
        ]
    [datasets.avslutta_videregaaende.thresholds_empty]
            fnr = 0.0

[datasets.avslutta_fagskole]

        variables = [
	        "fnr",
            "snr",
            "pers_foedselsdato",
            "pers_kjoenn",
            "utd_skoleaar_start",
            "utd_aktivitet_start",
            "utd_aktivitet_slutt",
            "utd_aktivitet_start_inn",
            "utd_aktivitet_slutt_inn",
            "utd_aktivitetsnivaa_heltid_deltid",
            "bof_orgnrbed",
            "utd_orgnr",
            "nus2000",
            "utd_datakilde",
            "utd_klassetrinn",
            "utd_utdanningstype",
            "utd_skolekom",
            "utd_fullfoertkode",
            "utd_viderutd_nettbasert",
            "fa_godkjent_fagskoleutd",
            "fa_studiestednr_inn",
            "fa_institusjon_id",
            "fa_karakter",
            "fuh_nett_eller_stedbasert",
        ]

    [datasets.avslutta_fagskole.thresholds_empty]
            fnr = 0.0


[datasets.avslutta_hoyereutdanning]

    variables = [
            "fnr",
            "snr",
            "pers_foedselsdato",
            "pers_kjoenn",
            "utd_skoleaar_start",
            "utd_aktivitet_start",
            "utd_aktivitet_slutt",
            "utd_aktivitet_start_inn",
            "utd_aktivitet_slutt_inn",
            "utd_aktivitetsnivaa_heltid_deltid",
            "bof_orgnrbed",
            "utd_orgnr",
            "nus2000",
            "utd_datakilde",
            "utd_klassetrinn",
            "utd_utdanningstype",
            "utd_skolekom",
            "utd_fullfoertkode",
            "utd_viderutd_nettbasert",
            "fuh_nett_eller_stedbasert",
            "uh_institusjon_id",
            "uh_statsborgerskap_inn",
            "uh_studierett",
            "uh_studienivaa",
            "uh_studieprogram",
            "uh_studieland",
            "uh_utland",
            "uh_fakultet",
            "uh_studiepoeng_grad",
        ]

    [datasets.avslutta_hoyereutdanning.thresholds_empty]
            fnr = 0.0



###########
# EKSAMEN #
###########



[datasets.eksamen_hoyereutdanning]

    variables = [
            "fnr",
            "snr",
            "pers_foedselsdato",
            "pers_kjoenn",
            "utd_skoleaar_start",
            "bof_orgnrbed",
            "utd_orgnr",
            "nus2000",
            "utd_datakilde",
            "utd_utdanningstype",
            "utd_skolekom",
            "utd_viderutd_nettbasert",
            "fuh_nett_eller_stedbasert",
            "uh_eksamen_dato",
            "uh_eksamen_dato_inn",
            "uh_antall_deleksamener",
            "uh_antall_deleksamener_bestatt",
            "uh_eksamen_er_gjentak",
            "uh_eksamen_karakter",
            "uh_eksamen_studpoeng",
            "uh_emnekode",
            "uh_emnekode_navn",
            "uh_institusjon_id",
            "uh_studienivaa",
            "uh_studieprogram",
            "uh_studieprogram_navn",
            "uh_studierett",
            "uh_termin_rapportert",
            "uh_fullfoertkode_inn",
        ]

    [datasets.eksamen_hoyereutdanning.thresholds_empty]
            fnr = 0.0
