###################
# Utdaterte/arkiv #
###################


	[variables.fnr_mrk_freg] # kobler fnr mot folkeregisteret?
		unit = "utdatert"
		dtype = "BOOLEAN"
		outdated_comment = "Bør holde med mangel på utfylt snr, kan bli nødvendig senere om vi fyller falsk snr"

	[variables.komp]
		unit = "utdatert"
		dtype = "STRING"
		length = [1]
		outdated_comment = "Bør utledes fra nus+klass istedenfor å ligge på filene?"

	[variables.foedselsaar]
		unit = "utdatert"
		dtype = "STRING"
		outdated_comment = "Vi ønsker fødselsdato på dataene, ikke fødselsaar."

	[variables.snr_nudb]
		unit = "utdatert"
		dtype = "STRING"
		length = [8]
		outdated_comment = "Etterlevning fra NUDB i Oracle. Bør fjernes og koble på snr+fnr isteden."

	[variables.aargang_start]
	# Should be reset from the path of the file (always the first year?)
		unit = "utdatert"
		dtype = "STRING"
		length = [4]
		renamed_from = ["aargang"]
		outdated_comment = "Årgang er ett forvirrende begrep, vi ønsker heller å benytte skoleaar_start eller skoleaar_slutt."

	[variables.rectype]
		unit = "utdatert"
		dtype = "STRING"
		length = [1]
		outdated_comment = "Rectype var for å skille eksamener fra avslutta-records. Eksamener er nå splittet til eget datasett. Denne er derfor undøvendig."

	[variables.inr]
		unit = "utdatert"
		dtype = "STRING"
		length = [7]
		outdated_comment = "“institusjonskode”? Identifiserer skoler før vi hadde tilgang på orgnr. INR ligger på eldre filer, bør koble på orgnr isteden, så fjerne INR."

    [variables.kilde_start]
        unit = "utdatert"
        dtype = "DATETIME"
		outdated_comment = "Blir denne benyttet? Vi trenger bedre config om hva den skal være"

    [variables.kilde_slutt]
        unit = "utdatert"
        dtype = "DATETIME"
		outdated_comment = "Blir denne benyttet? Vi trenger bedre config om hva den skal være"

    [variables.kilde_dato]
        unit = "utdatert"
        dtype = "DATETIME"
		outdated_comment = "Blir denne benyttet? Vi trenger bedre config om hva den skal være"

	[variables.utd_aktivitet_start_mrk_kilde]
		unit = "utdatert"
		dtype = "STRING"
		renamed_from = ["mrk_dl", "kurs_start_mrk_kilde"]
		outdated_comment = "“Merking av startdato” finnes kodeliste i gamle datadok-igang. Bør kunne hentes frem om det etterspørres, men vi lager nå datoer etter andre regler?"

	[variables.avgdato]
		unit = "utdatert"
        dtype = "STRING"
		outdated_comment = "Bør erstattes av utd_aktivitet_slutt"

	[variables.ftype]
		unit = "utdatert"
		dtype = "STRING"
		length = [1]
		klass_variant = 2942
		outdated_comment = "Splittes i kontraktstype og provekandtype avhengig av innfil den ligger på. En datasett-avhengig rename i datasets.toml bør konfigureres isteden."

    [variables.ftypef] # Samme som `ftype`?
        unit = "utdatert"
        dtype = "STRING"
        length = [1]
        klass_variant = 2942
		outdated_comment = "Splittes i kontraktstype og provekandtype avhengig av innfil den ligger på. En datasett-avhengig rename i datasets.toml bør konfigureres isteden."

	[variables.ktrinn]
		unit = "utdatert"
		dtype = "STRING"
		length = [2]
		outdated_comment = "Kan denne utledes fra nus? Om vi må ha programområdekode, så kan vi kanskje ikke få til det bakover i tid?"

	[variables.realkompetansevurdert_dato]
		unit = "utdatert"
		dtype = "DATETIME"
		renamed_from = ["dato_dokrealkomp"]
		outdated_comment = "Kommer på vg-dataene (resultatfag), hører til fag. Viser ikke det som er relevant, som er om realkompetansevurderingen har konsekvens for opptak til UH."

	# Ligger i rename av "utd_aktivitet_slutt" - isteden
    #[variables.fulldato]
    #    unit = "utdatert"
    #    dtype = "STRING"
	#	outdated_comment = "Tidsetting flyttet til andre tidskolonner. Se feks. utd_aktivitet_slutt. Stemmer best overens med 'sluttd'?"

    [variables.pedsem]
        unit = "utdatert"
        dtype = "STRING"
		outdated_comment = "Kan utledes fra NUS2000 isteden via gamle UHGRUPPE."

	[variables.voksen]
		unit = "utdatert"
		dtype = "BOOLEAN"
		outdated_comment = "Brukes kun for aldersavgrensning, alder bør regnes fra beviss refdato."

	[variables.sn72]
		unit = "utdatert"
		dtype = "STRING"
		length = [2]
		outdated_comment = "Bør kobles på fra BOF på nytt på orgnr, om nødvendig."


	[variables.sn78]
		unit = "utdatert"
		dtype = "STRING"
		length = [2]
		outdated_comment = "Bør kobles på fra BOF på nytt på orgnr, om nødvendig."

	[variables.sn94]
		unit = "utdatert"
		dtype = "STRING"
		length = [6]
		outdated_comment = "Bør kobles på fra BOF på nytt på orgnr, om nødvendig."

    [variables.sn07]
		unit = "utdatert"
		dtype = "STRING"
		length = [6]
		outdated_comment = "Bør kobles på fra BOF på nytt på orgnr, om nødvendig."

    [variables.sn25]
		unit = "utdatert"
		dtype = "STRING"
		length = [6]
		outdated_comment = "Bør kobles på fra BOF på nytt på orgnr, om nødvendig."

	# Mangler omdøping, skal flyttes til "utdatert"?
	[variables.mrk_dl1]
		unit = "utdatert"
		dtype = "STRING"
		outdated_comment = "Eldre merkevariabler, dårlig utfylt og lite tatt i bruk."

	[variables.mrk_dl2]
		unit = "utdatert"
		dtype = "STRING"
		outdated_comment = "Eldre merkevariabler, dårlig utfylt og lite tatt i bruk."

	[variables.mrk_dl3]
		unit = "utdatert"
		dtype = "STRING"
		outdated_comment = "Eldre merkevariabler, dårlig utfylt og lite tatt i bruk."

	[variables.mrk_per]
		unit = "utdatert"
		dtype = "STRING"
		outdated_comment = "Eldre merkevariabler, dårlig utfylt og lite tatt i bruk."

	[variables.mrk_end]
		unit = "utdatert"
		dtype = "STRING"
		outdated_comment = "Eldre merkevariabler, dårlig utfylt og lite tatt i bruk."

	[variables.mrk_grskole]
		unit = "utdatert"
		dtype = "STRING"
		outdated_comment = "Eldre merkevariabler, dårlig utfylt og lite tatt i bruk."


	# SKal sjekkes av AM
	[variables.spesund]
		unit = "utdatert"
		dtype = "STRING"
		length = [1]
		outdated_comment = "Usikker kvalitet blankt på de fleste årgangene - videregående opplæring"

	[variables.morsmal]
		unit = "utdatert"
		dtype = "STRING"
		length = [1]
		outdated_comment = "Usikker kvalitet blankt på de fleste årgangene - videregående opplæring"

	# Mangler omdøping, skal flyttes til "utdatert"?
	[variables.nus89]
		unit = "utdatert"
		dtype = "STRING"
		length = [6]
		outdated_comment = "Utdatert standard, korresponderer til nu standard?"

    [variables.fagkode]
		unit = "utdatert"
		dtype = "STRING"
		length = [3, 6, 7]
		outdated_comment = "Tilhører uavhengig tabell grunnskolekarakterer. Ikke nødvendig i NUDB?"

	[variables.i97isced]
		unit = "utdatert"
		dtype = "STRING"
		outdated_comment = "Kan kobles på NUS, ellers utdatert standard."

	[variables.i97destn]
		unit = "utdatert"
		dtype = "STRING"
		outdated_comment = "Kan kobles på NUS, ellers utdatert standard."

	[variables.i97orien]
		unit = "utdatert"
		dtype = "STRING"
		outdated_comment = "Kan kobles på NUS, ellers utdatert standard."

	[variables.i97grads]
		unit = "utdatert"
		dtype = "STRING"
		outdated_comment = "Kan kobles på NUS, ellers utdatert standard."

	[variables.i97varig]
		unit = "utdatert"
		dtype = "STRING"
		outdated_comment = "Kan kobles på NUS, ellers utdatert standard."

	[variables.kodetype]
		unit = "utdatert"
		dtype = "STRING"
		length = [1]
		outdated_comment = "Kan kobler på NUS"

	# Mangler omdøping, skal flyttes til "utdatert"?
	[variables.eierf]
		unit = "utdatert"
		dtype = "STRING"
		length = [1]
		klass_codelist = 793
		outdated_comment = "Bør kobles på fra BOF"

	[variables.sslag]
		unit = "utdatert"
		dtype = "STRING"
		outdated_comment = "Skoleslag? Mangler kodeliste? Kan heller bruke første siffer av nus2000. For øvrig inngår fagsole under videregående skole. Opprettes i samlingen"

	[variables.hoved]
		unit = "utdatert"
		dtype = "STRING"
		outdated_comment = "Lite bruk, bør kunne bruke NUS isteden? Bør denne heller ligge i NUSkatalogen, evt bare lage en en variant i klass under NUSkatalogen."

	[variables.uhgruppe]
		unit = "utdatert"
		dtype = "STRING"
		length = [3]
		outdated_comment = "Bør heller kobles på fra nus2000 enn ligge på datasettet?"

	[variables.vektgrad]
		unit = "utdatert"
		dtype = "FLOAT"
		outdated_comment = "Vi benytter nå studiepoeng, denne er utdatert."

	[variables.vekteks]
		unit = "utdatert"
		dtype = "FLOAT"
		outdated_comment = "Vi benytter nå studiepoeng, denne er utdatert."

    [variables.mrk_dl_bhu]
        unit = "utdatert"
        dtype = "STRING"
		outdated_comment = "Forteller om gyldigheten på tidsettingen på de eldre BHU-filene. 0: uendret tid, 1: juni dataens periode, 2: Ugyldig måned, men gyldig år, måned settes til juni, 3: tidsetting utenfor/etter range, settes til september dataens period, 4: Tidspunkt mangler, settes til 197011"

    [variables.endret_utfall]
        unit = "utdatert"
        dtype = "STRING"
		outdated_comment = "“Har fått endret utfallskode på avsluttadataene” - Tomt i alle årganger? Variabel benyttet under bygging av Avslutta? Bør ikke ligge i endelig fil"
